version: "3.8"

name: hsedb

services:
  db-migrator:
    # restart: always
    build:
      dockerfile: goose/Dockerfile
    command: ["postgresql://hseuser:hsepassword@db:5432/hsedb", "up"]
    depends_on:
      db:
        condition: service_healthy

  db:
   restart: always
   image: postgres:18
   environment:
     - POSTGRES_PASSWORD=hsepassword
     - POSTGRES_USER=hseuser
     - POSTGRES_DB=hsedb
   ports:
     - '6431:5432'
   healthcheck:
     test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
     interval: 10s
     timeout: 5s
     retries: 5
     start_period: 10s
